--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dirolov/Pictures/Wallpapers/wallpapersden.com_windows-11-4k-green-glow_3840x2400.jpg"

-- Special
background="#070f12"
foreground="#c1c3c3"
cursor="#c1c3c3"

-- Colors
color0="#070f12"
color1="#063C44"
color2="#0C4E4B"
color3="#136759"
color4="#119B5C"
color5="#23C253"
color6="#8AE45E"
color7="#c1c3c3"
color8="#56676a"
color9="#063C44"
color10="#0C4E4B"
color11="#136759"
color12="#119B5C"
color13="#23C253"
color14="#8AE45E"
color15="#c1c3c3"
