# Shell variables
# Generated by 'wal'
wallpaper="/home/dirolov/Pictures/Wallpapers/wallpapersden.com_windows-11-4k-green-glow_3840x2400.jpg"

# Special
background='#070f12'
foreground='#c1c3c3'
cursor='#c1c3c3'

# Colors
color0='#070f12'
color1='#063C44'
color2='#0C4E4B'
color3='#136759'
color4='#119B5C'
color5='#23C253'
color6='#8AE45E'
color7='#c1c3c3'
color8='#56676a'
color9='#063C44'
color10='#0C4E4B'
color11='#136759'
color12='#119B5C'
color13='#23C253'
color14='#8AE45E'
color15='#c1c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
